# Generated by Django 4.2.21 on 2025-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM (e.g., 2025-06-01 14:30). Optional.', null=True),
        ),
    ]
